Add support for Zsh

diff --git a/jirarc b/jirarc
--- a/jirarc
+++ b/jirarc
@@ -1,6 +1,17 @@
 #!/usr/bin/env bash
 #
 # Utility for automatically prefixing git commits with JIRA ticket names.
+#
+#
+# ZSH compatibility guide:
+#
+# ┌────────────────┬───────────────────────────┬──────────────────────────┐
+# │ FUNCTIONALITY  │ BASH SYNTAX               │ ZSH SYNTAX               │
+# ┝━━━━━━━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━┥
+# │ check shell    │ [ ${BASH_VERSION+x} = x ] │ [ ${ZSH_VERSION+x} = x ] │
+# ├────────────────┼───────────────────────────┼──────────────────────────┤
+# │ make uppercase │ ${var^^}                  │ ${var:u}                 │
+# └────────────────┴───────────────────────────┴──────────────────────────┘
 
 jira() {
     _jira_activate() {
@@ -8,12 +19,21 @@ jira() {
         then _jira_deactivate
         fi
 
-        export _jira_activated="${1^^}"
+        # ZSH COMPATIBILITY
+        if [ "${BASH_VERSION+x}" = "x" ]
+        then export _jira_activated="${1^^}"
+        elif [ "${ZSH_VERSION+x}" = "x" ]
+        then export _jira_activated="${1:u}"
+        else
+                echo "Cannot recognise shell - using Bash syntax" >&2
+                export _jira_activated="${1^^}"
+        fi
+
         export PS1="[$_jira_activated] $PS1"
 
         git() {
             command git "$@"
-            if [ "$1" == "commit" ] && [ "$?" == "0" ] && ! grep -F "[$_jira_activated]" <(git log --format=%B -n 1 2>&1) >/dev/null 2>&1
+            if [ "$1" = "commit" ] && [ "$?" = "0" ] && ! grep -F "[$_jira_activated]" <(git log --format=%B -n 1 2>&1) >/dev/null 2>&1
             then # commit message
                 EDITOR="sed -i '0,/^/s/^\\(\\[$_jira_activated\\] \\)\\?/\\[$_jira_activated\\] /'" command git commit --amend
             fi
